version: '3.0'

networks:
  access-log-net:
    driver: bridge
    ipam:
        config；
          - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

  services；
access-log-app1:
  build :
    context: xxxxxxx
    dockerfile: filename_xxxx
  image: access-log-app
  container_name: access-log-app1
  networks:
    - access-log-net
  ports:
    - 8081:8080/tcp
  restart: always
  depends_on:
    - nginx
    - redis
    - mysql

access-log-app2:
  build :
    context: xxxxxxx
    dockerfile: filename_xxxx
  image: access-log-app
  container_name: access-log-app2
  networks:
    - access-log-net
  ports:
    - 8081:8080/tcp
  restart: always
  depends_on:
    - nginx
    - redis
    - mysql

nginx:
  image: nginx:latest
  container_name: access-log-nginx-demo
  networks:
    - access-log-net
    ports:
      - 80:80/tcp
  restart: always
  volumes:
    - XXXXXpath:/afdlakjsfd

redis:
  image: redis:latest
  container_name: access-log-redis-demo
  networks:
    - access-log-net
  ports:
    - 6379:6379/tcp
  restart: always

mysql:
  image: mysql:latest
  container_name: access-log-mysql-demo
  networks:
    - access-log-net
  ports:
    - 3306:3306/tcp
  restart: always

volumes:
  access-log-service-demo-volume: {}